# ver 3.6 >= required: enable '-w' option for 'docker-compose exec'
version: "3.6"

volumes:
  # volume for db service container
  db-data:

services:
  # cli service container: node:12-alpine
  # $ docker-compose exec cli $command ...
  cli:
    build:
      context: ./ # build from ./Dockerfile
      args:
        # use current working user id
        UID: $UID
    logging:
      driver: json-file
    # tcp://localhost:<port> => service://cli:<port>
    network_mode: host
    # enable terminal
    tty: true
    volumes:
      # ./ => service:node:/work/
      - ./:/work/
    environment:
      TZ: Asia/Tokyo

  # db service container: mongo db v4.4
  db:
    image: mongo:4.4
    logging:
      driver: json-file
    # restart: always
    ports:
      # tcp://localhost:27017 => service://db:27017
      - 27017:27017
    volumes:
      # database data persistence
      - db-data:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  # admin service container: mongo-express:latest
  admin:
    image: mongo-express:latest
    logging:
      driver: json-file
    # restart: always
    links:
      - db
    ports:
      # http://localhost:8081 => service://admin:8081
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db # service://db
      ME_CONFIG_MONGODB_PORT: 27017
      TZ: Asia/Tokyo
